In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('heart_disease_uci.csv')

In [3]:
#Fixed the missing values
df = df.dropna()

In [4]:
df = pd.get_dummies(df, drop_first=True)

In [5]:
df.head()

,id,age,trestbps,chol,thalch,oldpeak,ca,num,sex_Male,dataset_Hungary,...,cp_non-anginal,cp_typical angina,fbs_True,restecg_normal,restecg_st-t abnormality,exang_True,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,1,63,145.0,233.0,150.0,2.3,0.0,0,True,False,...,False,True,True,False,False,False,False,False,False,False
1,2,67,160.0,286.0,108.0,1.5,3.0,2,True,False,...,False,False,False,False,False,True,True,False,True,False
2,3,67,120.0,229.0,129.0,2.6,2.0,1,True,False,...,False,False,False,False,False,True,True,False,False,True
3,4,37,130.0,250.0,187.0,3.5,0.0,0,True,False,...,True,False,False,True,False,False,False,False,True,False
4,5,41,130.0,204.0,172.0,1.4,0.0,0,False,False,...,False,False,False,False,False,False,False,True,True,False


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:-1], df.iloc[:,-1], test_size=0.2,random_state=2)

- imports the logistic regression algorithm class from the "linear_model" module of scikit-learn.
- LogisticRegression - classification of model (used for prediction categories like YES/NO, 0/1)
- imports the Decision Tree Classifier class from the tree module of scikit-learn.
- Tree based classification model.

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [8]:
 # model initialization (classifier)
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [9]:
# model training
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [10]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test, y_pred1))
print("Accuracy of DesicionTree", accuracy_score(y_test, y_pred2))

Accuracy of Logistic Regression 0.95
Accuracy of DesicionTree 0.9166666666666666


In [12]:
confusion_matrix(y_test, y_pred1)

array([[33,  3],
       [ 0, 24]])

In [13]:
print("Logistic Regession confusion Matrix : \n")
pd.DataFrame(confusion_matrix(y_test, y_pred1), columns=list(range(0,2)))

Logistic Regession confusion Matrix : 



,0,1
0,33,3
1,0,24


In [14]:
print("Decision Tree confusion Matrix : \n")
pd.DataFrame(confusion_matrix(y_test, y_pred2), columns=list(range(0,2)))

Decision Tree confusion Matrix : 



,0,1
0,33,3
1,2,22


In [15]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Predction:'] = y_pred1
result['Desicion Tree pediction :'] = y_pred2

Here we print the table from the sample data and predict it.

In [16]:
result.sample(10)

,Actual Label,Logistic Regression Predction:,Desicion Tree pediction :
293,True,True,True
135,False,False,False
100,False,False,False
224,False,False,False
161,False,False,False
10,False,True,True
288,True,True,True
286,False,True,True
153,True,True,True
277,False,False,False


In [17]:
from sklearn.metrics import recall_score, precision_score, f1_score

In [18]:
print("For the Logistic regression Model")
print("-"*50) #separator line
cdf = pd.DataFrame(confusion_matrix(y_test, y_pred1), columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision :", precision_score(y_test, y_pred1))
print("Recall : ", recall_score(y_test, y_pred1))
print("F1 Score", f1_score(y_test, y_pred1))

For the Logistic regression Model
--------------------------------------------------
    0   1
0  33   3
1   0  24
--------------------------------------------------
Precision : 0.8888888888888888
Recall :  1.0
F1 Score 0.9411764705882353


In [19]:
print("For the DecisionTree")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test, y_pred2), columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision :", precision_score(y_test, y_pred2))
print("Recall :", recall_score(y_test, y_pred2))
print("F1 Score :", f1_score(y_test, y_pred2))

For the DecisionTree
--------------------------------------------------
    0   1
0  33   3
1   2  22
--------------------------------------------------
Precision : 0.88
Recall : 0.9166666666666666
F1 Score : 0.8979591836734694


In [20]:
# calculates precision for each class separately using scikit-learn.
precision_score(y_test, y_pred1, average = None)

array([1.        , 0.88888889])

In [21]:
precision_score(y_test, y_pred2, average = None)

array([0.94285714, 0.88      ])

In [22]:
recall_score(y_test, y_pred1, average = None)

array([0.91666667, 1.        ])

In [23]:
recall_score(y_test, y_pred2, average = None)

array([0.91666667, 0.91666667])

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:-1], df.iloc[:,-1], test_size=0.2,random_state=2)

In [25]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [26]:
y_scores = model.predict_proba(X_test)[:,1]

In [27]:
y_scores

array([0.88452383, 0.05967725, 0.0540862 , 0.11177215, 0.77856964,
       0.02758469, 0.01810549, 0.68950336, 0.64508048, 0.02579498,
       0.77931101, 0.0177239 , 0.05954639, 0.03016959, 0.02701676,
       0.76723847, 0.08798376, 0.90055216, 0.6354682 , 0.02537134,
       0.05634413, 0.76547337, 0.86440899, 0.07394413, 0.01599322,
       0.86532887, 0.05079141, 0.86667697, 0.02959713, 0.15762521,
       0.94570003, 0.04754567, 0.87934187, 0.01979909, 0.03199619,
       0.02229732, 0.83983099, 0.81627017, 0.9273068 , 0.02746843,
       0.01905604, 0.05027931, 0.87959215, 0.0275247 , 0.53332844,
       0.03602598, 0.04130142, 0.04459468, 0.61016781, 0.79302859,
       0.02140313, 0.04161092, 0.77688548, 0.04511715, 0.90603166,
       0.87304217, 0.82435137, 0.77637558, 0.86642387, 0.02830355])

In [28]:
from sklearn.metrics import roc_curve
fpr , tpr, thresholds = roc_curve(y_test, y_scores)

In [29]:
thresholds

array([       inf, 0.94570003, 0.77856964, 0.76723847, 0.53332844,
       0.01599322])

In [30]:
import plotly.graph_objects as go
import numpy as np
from sklearn.metrics import roc_auc_score

# Assuming fpr, tpr, thresholds are already calculated as before
fpr, tpr, thresholds = roc_curve(y_test, y_scores)

# Calculate the AUC (Area Under the Curve)
roc_auc = roc_auc_score(y_test, y_scores)

# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name=f'ROC curve (Area = {roc_auc:.2f})'
)

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices],
    y=tpr[indices],
    mode='markers+text',
    name='Threshold points',
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]],
    textposition='top center'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()